name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install minimal dependencies for build - full install will happen at runtime
        pip install flask flask-basicauth python-dotenv
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Install Snapcraft (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo snap install snapcraft --classic
        
    - name: Build Electron app (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npm run build-linux
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Electron app (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run build-win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Electron app (macOS)
      if: matrix.os == 'macos-latest'
      run: npm run build-mac
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_IDENTITY_AUTO_DISCOVERY: false  # Disable code signing for now
        
    - name: Upload artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: agent-zero-linux
        path: |
          dist/*.AppImage
          dist/*.snap
          
    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: agent-zero-windows
        path: dist/*.exe
        
    - name: Upload artifacts (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: agent-zero-macos
        path: dist/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Display structure of downloaded files
      run: ls -R artifacts/
      
    - name: Prepare release assets
      run: |
        mkdir -p release/
        # Find and copy Linux artifacts
        find artifacts/agent-zero-linux -name "*.AppImage" -exec cp {} release/Agent-Zero-Linux.AppImage \; 2>/dev/null || true
        find artifacts/agent-zero-linux -name "*.snap" -exec cp {} release/ \; 2>/dev/null || true
        # Find and copy Windows artifacts  
        find artifacts/agent-zero-windows -name "*.exe" -exec cp {} release/Agent-Zero-Windows-Setup.exe \; 2>/dev/null || true
        # Find and copy macOS artifacts
        find artifacts/agent-zero-macos -name "*.dmg" -exec cp {} release/Agent-Zero-macOS.dmg \; 2>/dev/null || true
        ls -la release/
        
    - name: Create Release
      uses: ncipollo/create-release@v1
      with:
        tag: ${{ github.event.inputs.version || github.ref_name }}
        name: Agent Zero ${{ github.event.inputs.version || github.ref_name }}
        body: |
          # Agent Zero Desktop App Release
          
          ## Downloads
          - **Windows**: Download the `.exe` installer
          - **macOS**: Download the `.dmg` file  
          - **Linux**: Download the `.AppImage` or `.snap` package
          
          ## Installation
          - **Windows**: Run the installer and follow the setup wizard
          - **macOS**: Open the DMG file and drag Agent Zero to Applications
          - **Linux**: Make the AppImage executable with `chmod +x` and run it, or install the snap package
          
          ## What's New
          - Desktop application wrapper for Agent Zero
          - Cross-platform support (Windows, macOS, Linux)
          - Embedded Python server for seamless experience
          
          For full documentation, visit: https://github.com/K-Oz/a0
        draft: false
        prerelease: false
        artifacts: "release/*"
        token: ${{ secrets.GITHUB_TOKEN }}